name: Rust

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install stable toolchain and other components
      uses: actions-rs/toolchain@v1.0.5
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
    - name: format check
      run: |
        cargo fmt -- --check
    - name: linter
      run: cargo clippy
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install stable toolchain and other components
      uses: actions-rs/toolchain@v1.0.5
    - name: run unit test
      run: cargo test --all